apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  type: NodePort
  selector:
    app: postgres-deployment
  ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
        nodePort: 30432